version: '3.6'
services:
  barcode-api:
    image: node:16-alpine3.11
    environment:
      - NODE_ENV=development
    ports:
      - 3006:3006
    depends_on:
      - mysql-local
    working_dir: /usr/dock-bank/
    volumes: 
      - ./:/usr/dock-bank/
    command: ash -c "sleep 15 && ${CMD}"
  mysql-local:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: example-secure-password
      MYSQL_DATABASE: dock-bank
      MYSQL_USER: fake
      MYSQL_PASSWORD: fake
    ports:
      - 3306:3306