version: '3.6'
services:
  barcode-api:
    image: node:16-alpine3.11
    environment:
      - NODE_ENV=development
    working_dir: /usr/dock-bank/
    volumes: 
      - ./:/usr/dock-bank/
    command: ash -c "${CMD}"